/**
 * Custody of the database key (ADR-0011 section 2).
 *
 * The key is 32 random bytes generated on first run and kept in the macOS
 * Keychain, passed to SQLCipher as a raw key so no KDF runs at unlock (0.7 ms
 * versus 136 ms for a passphrase, per the spike). It is never derived from
 * anything the user types, which is the Bitwarden lesson ADR-0011 adopts:
 * a random data key means changing how the user unlocks never means
 * re-encrypting the corpus.
 *
 * ## What happens when the Keychain does not cooperate
 *
 * The decision this module makes, and the reason for it in each case:
 *
 * - **No key stored yet.** Generate one, store it, report `created: true`. This
 *   is first run. The caller checks whether a database file already exists: a
 *   newly created key plus an existing database means the old key is gone, and
 *   the store refuses to open rather than emitting `file is not a database`
 *   from somewhere deeper.
 * - **A key is stored but is not 32 bytes of hex.** Fail. Never regenerate:
 *   overwriting a key that might be the real one strands the database
 *   permanently, and a corrupt item is a situation a person should look at.
 * - **The Keychain refuses (denied, locked, any other error).** Fail, with the
 *   exit status and stderr. Never fall back to an unencrypted database and
 *   never fall back to a derived key; a privacy product that silently
 *   downgrades its own encryption is worse than one that stops.
 * - **The key is lost** (item deleted, Keychain reset, new machine). The
 *   database cannot be decrypted by anyone, including us. That is by design and
 *   the recovery is to delete the file and re-scan: the store is a derived
 *   cache and the user's documents are untouched (ADR-0007). No surface may
 *   present the store as a backup.
 *
 * ## Known limitation
 *
 * Storing goes through the `security` CLI, which takes the value as an argument,
 * so the key is briefly visible in the process table to other processes running
 * as the same user. Reading does not have this problem (the value comes back on
 * stdout). It is a small window and only on first run, and the adversary it
 * exposes us to (code already running as the user) is out of scope in
 * THREAT_MODEL.md, but it is a real edge and the fix is a native Security
 * framework call rather than a subprocess. Tracked separately.
 */

import { execFile } from 'node:child_process';
import { randomBytes as nodeRandomBytes } from 'node:crypto';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

/** Length of the raw database key, per ADR-0011. */
export const DATABASE_KEY_BYTES = 32;

/** Keychain service name the key is filed under. */
export const KEYCHAIN_SERVICE = 'outtray';

/** Keychain account name the key is filed under. */
export const KEYCHAIN_ACCOUNT = 'database-key';

/** `security` exit status for errSecItemNotFound. */
const ITEM_NOT_FOUND = 44;

/** A database key, and whether this call is the one that created it. */
export interface DatabaseKey {
  /** Raw key material, `DATABASE_KEY_BYTES` long. */
  key: Buffer;
  /** True when the key did not exist and was generated by this call. */
  created: boolean;
}

/** A swappable source of the database key (ADR-0011). */
export interface DatabaseKeyProvider {
  /** Stable identifier for logs, e.g. `keychain`. */
  readonly name: string;
  /**
   * Return the database key, creating and storing one on first run.
   *
   * Failure modes: rejects with `DatabaseKeyError` when a key exists but is
   * malformed, when the key store refuses access, or when the platform has no
   * supported key store. Never returns a key it derived from a fallback.
   */
  getOrCreateKey(): Promise<DatabaseKey>;
}

/** Thrown when the database key cannot be read, created or trusted. */
export class DatabaseKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DatabaseKeyError';
  }
}

/** Result of running the `security` command. */
export interface SecurityResult {
  status: number;
  stdout: string;
  stderr: string;
}

/** Runs `security` with the given arguments. Injected so the branches are testable. */
export type SecurityRunner = (args: readonly string[]) => Promise<SecurityResult>;

export interface KeychainKeyProviderOptions {
  /** Keychain service name. Defaults to `KEYCHAIN_SERVICE`. */
  service?: string;
  /** Keychain account name. Defaults to `KEYCHAIN_ACCOUNT`. */
  account?: string;
  /** Injected `security` runner (for tests). Defaults to the real subprocess. */
  run?: SecurityRunner;
  /** Injected platform (for tests). Defaults to `process.platform`. */
  platform?: NodeJS.Platform;
  /** Injected randomness (for tests). Defaults to `crypto.randomBytes`. */
  randomBytes?: (size: number) => Buffer;
}

/** Run the real `security` binary, mapping a non-zero exit to a result rather than a throw. */
const runSecurity: SecurityRunner = async (args) => {
  try {
    const { stdout, stderr } = await execFileAsync('security', [...args]);
    return { status: 0, stdout, stderr };
  } catch (error) {
    const err = error as { code?: number | string; stdout?: string; stderr?: string };
    return {
      status: typeof err.code === 'number' ? err.code : -1,
      stdout: err.stdout ?? '',
      stderr: err.stderr ?? String(error),
    };
  }
};

/** The database key held in the macOS Keychain (ADR-0011 section 2). */
export class KeychainKeyProvider implements DatabaseKeyProvider {
  readonly name = 'keychain';
  readonly #service: string;
  readonly #account: string;
  readonly #run: SecurityRunner;
  readonly #platform: NodeJS.Platform;
  readonly #randomBytes: (size: number) => Buffer;

  constructor(options: KeychainKeyProviderOptions = {}) {
    this.#service = options.service ?? KEYCHAIN_SERVICE;
    this.#account = options.account ?? KEYCHAIN_ACCOUNT;
    this.#run = options.run ?? runSecurity;
    this.#platform = options.platform ?? process.platform;
    this.#randomBytes = options.randomBytes ?? nodeRandomBytes;
  }

  async getOrCreateKey(): Promise<DatabaseKey> {
    if (this.#platform !== 'darwin') {
      throw new DatabaseKeyError(
        `The Keychain key provider needs macOS; this is ${this.#platform}. ADR-0011 targets ` +
          'macOS, and a non-macOS key store is a decision that has not been made.',
      );
    }
    const existing = await this.#find();
    if (existing) return { key: existing, created: false };
    const key = this.#randomBytes(DATABASE_KEY_BYTES);
    await this.#store(key);
    return { key, created: true };
  }

  /** Read the stored key, or null when there is none. */
  async #find(): Promise<Buffer | null> {
    const result = await this.#run([
      'find-generic-password',
      '-s',
      this.#service,
      '-a',
      this.#account,
      '-w',
    ]);
    if (result.status === ITEM_NOT_FOUND) return null;
    if (result.status !== 0) {
      throw new DatabaseKeyError(
        `Reading the database key from the Keychain failed (security exit ${result.status}): ` +
          `${result.stderr.trim() || 'no output'}. Outtray will not open the store without it, ` +
          'and will not fall back to an unencrypted database.',
      );
    }
    return this.#parse(result.stdout.trim());
  }

  /** Parse a stored hex key, rejecting anything that is not exactly the key. */
  #parse(hex: string): Buffer {
    const expected = DATABASE_KEY_BYTES * 2;
    if (hex.length !== expected || !/^[0-9a-fA-F]+$/.test(hex)) {
      throw new DatabaseKeyError(
        `The Keychain item ${this.#service}/${this.#account} is not a ${DATABASE_KEY_BYTES}-byte ` +
          'hex key. Outtray will not replace it, because overwriting a key that may still be the ' +
          'real one would make the store permanently unreadable. Inspect the item in Keychain ' +
          'Access; if the store is expendable, delete both it and the item and re-scan.',
      );
    }
    return Buffer.from(hex, 'hex');
  }

  /** Store a freshly generated key. */
  async #store(key: Buffer): Promise<void> {
    const result = await this.#run([
      'add-generic-password',
      '-s',
      this.#service,
      '-a',
      this.#account,
      '-w',
      key.toString('hex'),
      '-U',
    ]);
    if (result.status !== 0) {
      throw new DatabaseKeyError(
        `Storing the database key in the Keychain failed (security exit ${result.status}): ` +
          `${result.stderr.trim() || 'no output'}.`,
      );
    }
  }
}

/**
 * A key supplied directly, for tests and for callers that hold their own.
 *
 * Not a fallback for the Keychain: nothing constructs this on the user's
 * behalf, so there is no path where a real store silently opens with a key that
 * did not come from the Keychain.
 */
export class StaticKeyProvider implements DatabaseKeyProvider {
  readonly name = 'static';
  readonly #key: Buffer;
  readonly #created: boolean;

  /**
   * Failure modes: throws `DatabaseKeyError` if `key` is not
   * `DATABASE_KEY_BYTES` long, so a short test key cannot quietly become a
   * different security posture than the real one.
   */
  constructor(key: Buffer, created = false) {
    if (key.byteLength !== DATABASE_KEY_BYTES) {
      throw new DatabaseKeyError(
        `A database key must be ${DATABASE_KEY_BYTES} bytes; got ${key.byteLength}.`,
      );
    }
    this.#key = Buffer.from(key);
    this.#created = created;
  }

  async getOrCreateKey(): Promise<DatabaseKey> {
    return { key: Buffer.from(this.#key), created: this.#created };
  }
}

/** Generate a fresh database key. Exposed for tests and for `StaticKeyProvider` callers. */
export function generateDatabaseKey(): Buffer {
  return nodeRandomBytes(DATABASE_KEY_BYTES);
}
